name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  test-build-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          token: a1b2c3d4e5f67890123456789abcdef0
          subscriptionCode: 458eba4f7e7cdaa9f9275c22c2dc9cbc
          branch: release/v1.0.0
          buildName: Release v1.0.0
          checkStatusInterval: 60000
          retryOnFailure: true
          maxRetries: 5
          notify: true
          webhookUrl: https://webhook.site/1b1b1b1b-1b1b-1b1b-1b1b-1b1b1b1b1b1b

      - name: Print Output
        id: output
        run: |
          echo "Build Code: ${{ steps.test-action.outputs.buildCode }}, Build Status: ${{ steps.test-action.outputs.buildStatus }}"